apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-customer
  template:
    metadata:
      labels:
        app: my-customer
    spec:
      containers:
      - name: my-customer
        image: amigoscode/kubernetes:customer-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ORDER_SERVICE
            value: my-order-service    
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: my-customer-service
spec:
  type: NodePort
  selector:
    app: my-customer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000

