apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-c
  template:
    metadata:
      labels:
        app: frontend-c
    spec:
      containers:
      - name: frontend-c
        image:  amigoscode/kubernetes:frontend-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
