apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-order
  template:
    metadata:
      labels:
        app: my-order
    spec:
      containers:
      - name: my-order
        image: amigoscode/kubernetes:order-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: my-order-service
spec:
  selector:
    app: my-order
  ports:
  - port: 80
    targetPort: 8081

