apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-c
  template:
    metadata:
      labels:
        app: order-c
    spec:
      containers:
      - name: order-c
        image: amigoscode/kubernetes:order-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order-c
  ports:
  - port: 80
    targetPort: 8081

